-- the entire code works perfectly on MySQL

DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Block_Stall;
DROP TABLE IF EXISTS ParkingLot_Block;
DROP TABLE IF EXISTS ParkingLot;
DROP TABLE IF EXISTS ShortTermPass;
DROP TABLE IF EXISTS LongTermPass;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Employee;

